### ISSUE TITLE
What is our stance on Visual Regression Testing?

### ISSUE THREAD

**Issue by marhigh** [simplabs/playbook#101]
I have seen a lot of teams struggle when they don't have visual regression testing. It helps a lot when doing design system QA (or visual design QA in general). 

Do we have an opinion on it? Would it make sense to include as a recommended practice?

**Comment by marcoow** [comment]
Yes, good point – that could be a section under [Testing](https://github.com/simplabs/playbook/tree/master/src/development-process#testing)
