### ISSUE TITLE
Rename "user stories" to "feature concepts"

### ISSUE THREAD

**Issue by marcoow** [simplabs/playbook#110]
Currently we're talking about _"user stories"_ without actually meaning what that term usually stands for. We should find a better term that is not already commonly used for something else and that expresses more clearly what we're trying to say.

> I think part of the confusion around this is maybe caused by the playbook using _"user story"_ in a non-standard way since we're not actually talking about the standard diagrams etc. that are used for that. In the latest version of my talk, I use _"feature concepts"_ instead which (I think) is not a defined term that could lead to confusion. Maybe that term (or a different one) would be better to use in the playbook as well.

Agreed!

_Originally posted by @marhigh in https://github.com/simplabs/playbook/pull/100#issuecomment-701433798_

**Comment by marcoow** [comment]
@marhigh do you think _"feature concept"_ is good or shall we think about that a bit more?

**Comment by marhigh** [comment]
@marcoow I think it's a good term 👌

**Comment by marcoow** [comment]
@JaninaBodi can you do this? We basically just need to replace all occurences of _"user story"_, _"user stories"_ etc. I think we **might** be just using _"stories"_ or so sometimes so simple search/replace might not find all occurences.
